FROM golang as builder

ENV GO111MODULE=on

WORKDIR /go-modules-docker

COPY . .

WORKDIR /go-modules-docker/go-modules

# RUN go mod download

RUN go build -o /go-modules-docker/hello-world

FROM alpine:3.8

WORKDIR /root/

COPY --from=builder /go-modules-docker/hello-world .

CMD ["./hello-world"]