FROM golang:1.13-alpine 

RUN apk --update --no-cache add tar gcc bash musl-dev ca-certificates git openssh linux-headers && rm -rf /var/cache/apk/*

# Set the Current Working Directory inside the container
WORKDIR $GOPATH/src/github.com/slns/go-hello-world

# Copy everything from the current directory to the PWD (Present Working Directory) inside the container
COPY . .

# Download all the dependencies
RUN go get -d -v ./...

# Install the package
RUN go install -v ./...

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Run the executable
CMD ["go-hello-world"]